name: carousel_slider
description: A carousel slider widget, support infinite scroll and custom child widget.
author: serenader <xyslive@gmail.com>
homepage: https://github.com/serenader2014/flutter_carousel_slider
version: 1.3.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter_web: any

dev_dependencies:
  flutter_web_test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
